
spring.application.name=usuario
spring.web.error.include-binding-errors=always
spring.web.error.include-message=always

# ===================================================================
# CONFIGURACIÓN DINÁMICA DE BASE DE DATOS (MIGRACIÓN DOCKER/LOCAL)
# ===================================================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/full_stack_usuario?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:full_stack_1}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Tav_2026.@}
spring.datasource.driver-class-name=${SPRING_DRIVER_CLASS:org.postgresql.Driver}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
# ===================================================================

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
server.port=5000
springdoc.swagger-ui.path=/usuario.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operations-sorter=Alpha
app.name=Gestion de usuarios
app.version=3.0.0